### ISSUE TITLE
Feature request - VATs for countries

### ISSUE THREAD

**Issue by jdinse** [hexorx/countries#219]
Is there any gem to get VATs for a country? We consider to build it on our own if there is none.

**Comment by rposborne** [comment]
We already have it! It's just not documented. All EU countries have the following

``` yaml
vat_rates:
    standard: 19
    reduced:
    - 7
    super_reduced: 
    parking: 
```
