### ISSUE TITLE
Translation of nationality into different languages

### ISSUE THREAD

**Issue by paolodona** [hexorx/countries#349]
I use the country gem to provide my users with the ability to specify their nationality.
At the moment, the list of nationalities is taken from the nationality attribute.

Users in different locales do not have the list translated into their own language, so I would like to add the ability to get the country.nationality in different languages, eg by switching locale:

```
Country['IT'].nationality #=> "Italian"
I18n.locale = :it
Country['IT'].nationality #=> "Italiana"
```

or by explicitly requesting the translation for a given locale:

```
Country['IT'].nationality()     #=> "Italian"
Country['IT'].nationality(:en)  #=> "Italian"
Country['IT'].nationality(:it ) #=> "Italiana"
```

I'm happy to work on a PR to implement this, but I would like to know what is the preferred way to store this info in the data files, the options I see are:

* add a nationalities key in the main data files, with all the translations eg:

```
---
IT:
  continent: Europe 
  alpha2: IT
  name: Italy
  nationality: Italian
  nationalities:
    it: Italiana
    fr: Italien 
    ...
```

* or create a new set of files altogether, such as:

```
# lib/countries/data/nationalities/IT.yaml
IT:
  nationalities:
    it: Italiana
    fr: Italien 
    ...
```

If you give me an idea of what is the preferred way, I will be happy to implement this and make sure that localised nationalities fall back to english should a translation not exist.

My personal preference would be:
* keep all info into the main data file, so contributors have an easier time filling it in
* automatically return the localised nationality based on current I18n.locale
but I'm open to other suggestions.
